### ISSUE TITLE
limit and offset should be ?int

### ISSUE THREAD

**Issue by carlcasbolt** [robinkashyap-01/simple-query-builder#1]
https://github.com/robinkashyap-01/simple-query-builder/blob/d903eef544d87fb4ca26dbbca05774efa60f6875/src/Query.php#L22C22-L22C22

You allow any value for the limit and offset, you should be enforcing `?int` which will stop the use of floats, strings or arrays on your query builder.

You might also want to think about value checking and not allow negative numbers or a limit of 0 as that wouldn't be valid SQL

**Comment by gurpreetkaits** [comment]
Thanks for advice, I'll be improving the structure as well. 

For example, If I'll install this via composer then how should I ask for connection details?

I'm confused about it

**Comment by gurpreetkaits** [comment]
Changing the structure
